name: Openwrtx64
on: 
  release:
    types: [published]

  #push:
   # branches: 
    #  - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_NAME: openwrt
  CONFIG_FILE: x86_64.config
  DIY_SH: diy.sh
  #FREE_UP_DISK: false
  #SSH_ACTIONS: false
 # UPLOAD_BIN_DIR: false
#  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        #docker rmi `docker images -q`
        #sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Clone source code
      run: | 
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH $REPO_NAME
         cd $REPO_NAME/package
         git clone https://github.com/Lienol/openwrt-package Lienol
    - name: download dl
      env: 
       REPO_URL1: https://image.moeclub.org/GoogleDrive/
       REPO_URL2: 1VZHn2AJ3iXpJAYsDwWAPL6m_CjMAovsb
       REPO_NAMES: dl.tar.gz
      run: | 
        cd $REPO_NAME
        wget  $REPO_URL1/$REPO_URL2
        mv  $REPO_URL2 $REPO_NAMES
        tar -xzvf $REPO_NAMES
        sudo rm -rf $REPO_NAMES
        sed -i 's/192.168.1.1/192.168.0.100/g' package/base-files/files/bin/config_generate     
    - name: Update & Install feeds
      run: |
        cd $REPO_NAME 
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Configuration Customization - Build_x64
      run: |
       # [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $REPO_NAME/.config
       # chmod +x $DIY_SH
        #cd $REPO_NAME
       # ../$DIY_SH
       # make defconfig  
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin             
   # - name: SSH connection to Actions
    #  uses: P3TERX/debugger-action@master   
